export type TechName =
	| 'Next.js'
	| 'Tailwind CSS'
	| 'Supabase'
	| 'Zustand'
	| 'GSAP'
	| 'Lenis'
	| 'Node.js'
	| 'Express'
	| 'React'
	| 'SQLite'
	| 'dnd kit'
	| 'Motion'
	| 'yt-dlp'
	| 'TypeScript'
	| 'MongoDB'
	| 'Jest'
	| 'JWT'
	| 'Mongoose'
	| 'OpenAPI'
	| 'Swagger UI'
	| 'Docker'
	| 'Redux Toolkit'
	| 'React Testing Library'
	| 'Electron'
	| 'Storybook'
	| 'Celebrate (Joi)'
	| 'Spotify Web API'
	| 'Spotify Web Playback SDK'
	| 'React Infinite Scroller'
	| 'better-sqlite3'
	| 'AES-GCM'
	| 'PBKDF2'
	| 'Argon2id'
	| 'bcrypt.js';
